# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.labelTitle = QtWidgets.QLabel(parent=Form)
        self.labelTitle.setGeometry(QtCore.QRect(130, 30, 121, 16))
        self.labelTitle.setObjectName("labelTitle")
        self.labelId = QtWidgets.QLabel(parent=Form)
        self.labelId.setGeometry(QtCore.QRect(70, 70, 16, 16))
        self.labelId.setObjectName("labelId")
        self.lineEditId = QtWidgets.QLineEdit(parent=Form)
        self.lineEditId.setGeometry(QtCore.QRect(120, 70, 113, 20))
        self.lineEditId.setObjectName("lineEditId")
        self.labelCandidates = QtWidgets.QLabel(parent=Form)
        self.labelCandidates.setGeometry(QtCore.QRect(140, 120, 71, 16))
        self.labelCandidates.setObjectName("labelCandidates")
        self.radioJane = QtWidgets.QRadioButton(parent=Form)
        self.radioJane.setGeometry(QtCore.QRect(140, 150, 61, 17))
        self.radioJane.setObjectName("radioJane")
        self.radioJohn = QtWidgets.QRadioButton(parent=Form)
        self.radioJohn.setGeometry(QtCore.QRect(140, 190, 82, 17))
        self.radioJohn.setObjectName("radioJohn")
        self.pushButtonSubmit = QtWidgets.QPushButton(parent=Form)
        self.pushButtonSubmit.setGeometry(QtCore.QRect(110, 232, 131, 31))
        self.pushButtonSubmit.setObjectName("pushButtonSubmit")
        self.labelMessage = QtWidgets.QLabel(parent=Form)
        self.labelMessage.setGeometry(QtCore.QRect(100, 270, 101, 21))
        self.labelMessage.setText("")
        self.labelMessage.setObjectName("labelMessage")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.labelTitle.setText(_translate("Form", "VOTING APPLICATION"))
        self.labelId.setText(_translate("Form", "ID"))
        self.labelCandidates.setText(_translate("Form", "CANDIDATES"))
        self.radioJane.setText(_translate("Form", "Topuria"))
        self.radioJohn.setText(_translate("Form", "Gaethje"))
        self.pushButtonSubmit.setText(_translate("Form", "SUBMIT VOTE"))
